name:                Frames-hvega
version:             0.1.0.0
github:              "adamConnerSax/Frames-hvega"
license:             BSD3
author:              "Adam Conner-Sax"
maintainer:          "adam_conner_sax@yahoo.com"
copyright:           "2019 Adam Conner-Sax"

extra-source-files:
- Readme.md
- ChangeLog.md

synopsis:            Tools for using hvega with data stored in a Frame or other Foldable container of vinyl records.
category:            Graphics, Visualization

description:         Please see the README on GitHub at <https://github.com/adamConnerSax/Frames-hvega#readme>

dependencies:
- array >= 0.4.0.1 && <= 0.6
- base >= 4.7 && < 5
- containers >= 0.5.0.0 && <= 0.7
- foldl >= 1.4.0 && <= 1.5
- Frames >= 0.5.0 && <= 0.7
- Frames-utils >= 0.2.0.1 && < 0.4
- histogram-fill >= 0.8.0.0 && < 0.10
- hvega >= 0.2.0.0 && < 0.5
- statistics >= 0.15.0 && < 0.16
- text >= 1.1.0.1 && < 1.3
- time >= 1.8 && <= 1.10
- vector >= 0.11.0.0 && < 0.13
- vinyl >= 0.10.0 && < 0.12

flags:
  dump-core:
    description: Dump HTML for the core generated by GHC during compilation
    default:     False
    manual:      True

library:
  ghc-options: -O -Wall
  source-dirs: src

  when:
    - condition: flag(dump-core)
      dependencies:
        - dump-core
      ghc-options:
        - -fplugin=DumpCore
        - -fplugin-opt DumpCore:core-html

